apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::557690607676:user/flaskstack
      username: github-ci
      groups:
        - system:masters
