environment: dev

global:
  image:
    repository: 557690607676.dkr.ecr.us-east-2.amazonaws.com/flaskstack-ecr
    pullPolicy: IfNotPresent

environments:
  dev:
    image:
      tag: latest
    replicaCount: 1
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"

  staging:
    image:
      tag: staging-20240523
    replicaCount: 2
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"

env:
  POSTGRES_HOST: postgresql
  POSTGRES_DB: app
  POSTGRES_USER: user
  POSTGRES_PASSWORD: strong-password

ingress:
  enabled: true
  host: flaskstack.app.com

awsAuth:
  mapRoles:
    - rolearn: "arn:aws:iam::557690607676:role/eks-nodegroup-role"
      groups:
        - "system:bootstrappers"
        - "system:nodes"
  mapUsers:
    - userarn: "arn:aws:iam::557690607676:user/flaskstack"
      username: "flaskstack"
      groups:
        - "system:masters"


rbac:
  clusterRoleBinding:
    enabled: true
    name: flaskstack-admin-binding
    subjects:
      - kind: User
        name: flaskstack       # זה שם המשתמש בקוברנטיס (מתאים למה שמוגדר ב-aws-auth)
        apiGroup: rbac.authorization.k8s.io
    roleRef:
      kind: ClusterRole
      name: cluster-admin
      apiGroup: rbac.authorization.k8s.io
