environment: dev

global: 
  image: 
    repository: yakiradela/flaskstack
    pullPolicy: IfNotPresent

environments:
  dev:
    image:
      tag: latest
    replicaCount: 1
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"

  staging:
    image:
      tag: staging-20240523
    replicaCount: 2
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"

env: 
  POSTGRES_HOST: postgresql
  POSTGRES_DB: app 
  POSTGRES_USER: user
  POSTGRES_PASSWORD: pass-from-secret

ingress:
  enabled: true
  host: flaskstack.app.com
