apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: bitnami/postgres:14  # תמונה עם postgres ויותר כלים, או לשלב awscli
              env:
                - name: PGHOST
                  value: "postgres-postgresql-ha-postgresql"  # תיקנתי את השם
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: flaskstack-app-secret
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: flaskstack-app-secret
                      key: password
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-secret
                      key: awsAccessKeyId  # וודא שהמפתח נכון במפתח הסוד
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-secret
                      key: awsSecretAccessKey
                - name: S3_BUCKET
                  value: "db-backups"
              command:
                - /bin/sh
                - -c
                - |
                  export FILENAME=backup_$(date +%Y-%m-%d_%H-%M-%S).sql.gz
                  pg_dump -U $PGUSER -h $PGHOST | gzip > /tmp/$FILENAME
                  aws s3 cp /tmp/$FILENAME s3://$S3_BUCKET/$FILENAME
          restartPolicy: OnFailure
