apiVersion: batch/v1
kind: Cronjob 
metadata:
  name: postgres-buckup
spec: 
  schedule: "0 */6 * * *"
  jobTemplate:
    spec: 
      template:
        spec: 
          containers:
            - name: buckup 
              image: postgres:14
              env:
                - name: PGHOST 
                  value: "postgres-postfresql-ha-postfresql"
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: flaskstack-app-secret
                      key: username 
                - name: PGPASSWORD 
                  valueFrom: 
                    secretKeyRef:
                      name: flaskstack-app-secret
                      key: password 
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-buckup-secret
                      key: awsSecretAccessKey
                - name: S3_BUCKET
                  value: "db-backups" 
              command:
                - /bin/sh
                - -c
                - |
                  export FILENAME=backup_$(date +%Y-%m-%d_%H-%M-%S).sql.gz
                  pg_dump -U $PGUSER | gzip > /tmp/$FILENAME
                  aws s3 cp /tmp/$FILENAME s3://$S3_BUCKET/$FILENAME
          restartPolicy: OnFailure                                
