postgresql:
  username: user
  password: strong-password
  database: app 

replicaCount: 2

pgpool:
  replicaCount: 2
  resources:
    requests:
      cpu: 200m
      memory: 256Mi

presistence:
  enabled: true
  size: 10Gi
  strogeClass: gp2

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 30s
    scrapeTimeout: 10s

resources:
  requests:
    cpu: 250m 
    memory: 512Mi 

tls: 
  enabled: false

existingSecret: ""  
