apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: {{ .Values.awsAuth.roleArn }}
      username: github-actions
      groups:
        - system:masters
