apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: {{ .Values.awsAuth.roleArn }}
      username: github-actions
      groups:
        - system:masters
