apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
{{- range .Values.awsAuth.mapRoles }}
    - rolearn: {{ .rolearn | quote }}
      username: {{ .username | default "system:node:{{EC2PrivateDNSName}}" | quote }}
      groups:
{{- range .groups }}
        - {{ . | quote }}
{{- end }}
{{- end }}
  mapUsers: |
{{- range .Values.awsAuth.mapUsers }}
    - userarn: {{ .userarn | quote }}
      username: {{ .username | quote }}
      groups:
{{- range .groups }}
        - {{ . | quote }}
{{- end }}
{{- end }}
