apiVersion: v1
kind: configMap
metadata:
  name: flaskstack
  labels:
    app: flaskstack
data:
    ENVIRONMENT: {{ .Values.environment | quote}}
    POSTGRES_DB: {{ .Values.env.POSTGRES_DB | quote }}
    POSTGRES_HOST: {{ .Values.env.POSTGRES_USER | quote }}
    POSTGRES_HOST: {{ .Values.env.POSTGRES_USER | quote }}
