apiVersion: apps/v1
kind: deployment
metadata:
  name: flaskstack-dep
spec:
  replicas: {{ index .Values.environments .Values.environment "replicaCount" }}
  selector:
    matchLabels:
      app: flaskstack
  template:
    metadata:
      labels:
        app: flaskstack
    spec:
        containers:
            - name: flaskstack
              image: "{{ .Values.global.image.repository }}:{{ .Values.environments.[.Values.environment].iamge.tag }}"
              imagePullPolicy: "{{ .Values.global.image.imagePullpolicy }}"
              ports:
                - containerPort: 5000
              envFrom:
                - configMapRef:
                    name: flaskstack
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: flaskstack
                      key: flaskstack
              resources:
                {{- toYaml .Values.environment.[.Values.environment].resources | nindent 12 }}


