apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskstack-dep
spec:
  replicas: {{ index .Values.environments .Values.environment "replicaCount" }}
  selector:
    matchLabels:
      app: flaskstack
  template:
    metadata:
      labels:
        app: flaskstack
    spec:
      containers:
        - name: flaskstack
          image: "{{ .Values.global.image.repository }}:{{ index .Values.environments .Values.environment "image" "tag" }}"
          imagePullPolicy: "{{ .Values.global.image.pullPolicy }}"
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: flaskstack
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flaskstack
                  key: flaskstack
          resources:
            {{- toYaml (index .Values.environments .Values.environment "resources") | nindent 12 }}


