apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flaskstack-ingress
  annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      {{- if eq .Values.environment "prod" }}
      cert-manager.io/cluster-issuer: "letsencryptprod"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      {{- end }}
spec:
  {{-if eq .Values.environment "prod" }}
  tls:
      - hosts:
          - flaskstack.app.com
        secretName: flaskstack-app-tls
  {{-end }}
  rules:
      - host: flaskstack.app.com
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: flaskstack
                   port: 
                      number: 80
