apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: {{ if eq .Values.environment "prod" }}LoadBalancer{{ else }}ClusterIP{{ end }}
